### ISSUE TITLE
API#add_contact method mutates parameters due to String#escape! usage

### ISSUE THREAD

**Issue by torce** [ssut/telegram-rb#24]
When the method `add_contact` is called, the parameters `first_name` and `last_name` are mutated since they are escaped inside the method.

I don't know if this is the expected behaviour, but it seems a bit strange to me. Our current workaround is to call `dup` on the parameters that will be mutated inside the method to avoid side effects.

`API#create_group_chat` and `API#msg` have the same problem with their parameters.

A small sample that shows the problem:

``` ruby
EM.run do
  telegram = Telegram::Client.new do |cfg|
    cfg.daemon = '/path/to/tg/bin/telegram-cli'
    cfg.key = '/path/to/tg/tg-server.pub'
  end

  Contact = Struct.new(:phone_number, :first_name, :last_name)
  contact = Contact.new('XXXxxxXXXxxx', 'First name', 'Last name')

  telegram.connect do
    telegram.add_contact(contact.phone_number, contact.first_name, contact.last_name) do |success, response|
      p contact #<struct Contact first_name="\"First name\"", last_name="\"Last name\"">
    end
  end
end
```

I think that this can be solved in several ways (I will make a PR if you want):
- Show in the documentation that the parameters will be mutated (if this behaviour is intended).
- Replace `String#escape!` with a side-effect free version: `String#escape`.
- Add a side-effect free version besides the current method `String#escape!` in the case of a side-effect escape method was required for some reason.

Thank you for your time.

**Comment by ssut** [comment]
Oops, this is not what I expected. Thank you for your reporting and here I can say that I cannot fix this problem right now, as it was then, therefore if you can make a PR to fix this issue it would be highly appreciated and I will merge it asap.
