### ISSUE TITLE
 telegram cli not found

### ISSUE THREAD

**Issue by mm580486** [ssut/telegram-rb#4]
hi friends :)
i have problem in run example.rb

example.rb:
  # encoding: utf-8
lib = File.join(File.dirname(**FILE**), 'lib')
$:.unshift lib unless $:.include?(lib)

require 'eventmachine'
require 'telegram'

EM.run do
  telegram = Telegram::Client.new do |cfg|
    cfg.daemon = '/tg/telegram-cli'
    cfg.key = '/tg/tg-server.pub'
  end

  telegram.connect do
    puts telegram.profile
    telegram.contacts.each do |contact|
      puts contact
    end
    telegram.chats.each do |chat|
      puts chat
    end

```
telegram.on[Telegram::EventType::RECEIVE_MESSAGE] = Proc.new { |ev|

}
```

  end
end

bash:
mohammads-MacBook-Pro:telegram mohammad$ ruby example.rb 
[2015-10-23 10:57:47] INFO  (Telegram::Client): Initialized
[2015-10-23 10:57:47] INFO  (Telegram::Client): Trying to start telegram-cli and then connect
sh: /tg/telegram-cli: No such file or directory
/Users/mohammad/Desktop/telegram/lib/telegram/client.rb:80:in `readline': end of file reached (EOFError)
    from /Users/mohammad/Desktop/telegram/lib/telegram/client.rb:80:in`block in execute'
    from /Users/mohammad/Desktop/telegram/lib/telegram/client.rb:79:in `loop'
    from /Users/mohammad/Desktop/telegram/lib/telegram/client.rb:79:in`execute'
    from /Users/mohammad/Desktop/telegram/lib/telegram/client.rb:156:in `connect'
    from example.rb:14:in`block in <main>'
    from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `call'
    from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in`run_machine'
    from /Library/Ruby/Gems/2.0.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:193:in `run'
    from example.rb:8:in`<main>'

**Comment by mm580486** [comment]
i not found telegram-cli folder !

**Comment by ssut** [comment]
Please check the specified telegram daemon on `cfg.daemon = '/tg/telegram-cli'`

**Comment by mm580486** [comment]
where is telegram-cli path?

**Comment by ssut** [comment]
Check this: https://github.com/vysheng/tg

**Comment by mm580486** [comment]
i downloaded this url , i found tg-server.pub but not found cfg.daemon = '/tg/telegram-cli' !

**Comment by ssut** [comment]
Since you have downloaded it you have to compile it as executable and change the path to its location like `/path/to/tg/bin/telegram-cli`. Please read the README file.

**Comment by mm580486** [comment]
have you team viewer ?
