### ISSUE TITLE
루비 버젼 몇 기준으로 작성된건가요?

### ISSUE THREAD

**Issue by tatsuo-ike** [ssut/telegram-rb#5]
2.3.0 에서 샘플 코드가 실행은 되는데, 실행후에 아래와 같이 출력 후 아무런 액션도 일어나지 않습니다.

> [2016-02-05 01:10:02] INFO  (Telegram::Client): Initialized
> [2016-02-05 01:10:02] INFO  (Telegram::Client): Trying to start telegram-cli and then connect
> [2016-02-05 01:10:02] INFO  (Telegram::Client): Successfully connected to the Telegram CLI
> [2016-02-05 01:10:02] INFO  (Telegram::Client): Start polling for events

**Comment by ssut** [comment]
루비 2.1.0 버전 이상에서 테스트가 진행되었습니다. 현재 이 코드를 이용해 텔레그램 봇을 돌리고 있는 상태이기도 합니다.
해당 과정 이후 진행이 되지 않는다면 telegram-cli 문제일 가능성이 큽니다. telegram-cli 레포에서 test 브랜치로 컴파일한 후에 다시 시도해보신 후 그래도 작동하지 않는다면 구동 환경을 알려주시면 확인해보도록 하겠습니다. 테스트가 진행된 OS는 OS X 10.11, 우분투 14.04 LTS 입니다.
