### ISSUE TITLE
add Telegram::Client#disconnect

### ISSUE THREAD

**Issue by alexanderadam** [ssut/telegram-rb#6]
Hi @ssut,

I would love too see an explicit `#disconnect` method or is there any other graceful disconnect possibility at the moment?

Thank you very much

**Comment by ssut** [comment]
Hello there,

No way right now, I've been trigging a keyboard interrupt when I need to stop it. If you are going to make a pull request it would be appreciated.

**Comment by alexanderadam** [comment]
I'm also triggering a keyboard interrupt but I'm using a [trap context)](http://ruby-doc.org/core-2.2.0/Signal.html#method-c-trap) where I'm triggering cleaning up (closing files, closing sockets etc. like `trap('INT') { telegram_client.disconnect }`). 

Anyway I saw that @GeNiuS69 implemented the [trigger for a graceful disconnect](https://github.com/GeNiuS69/telegram-rb/commit/15d49fa100b06ffdf3dcc1140b1f01bc4b96c814) and I asked him about making a PR already (this is why you should see the comment reference about your answer).

**Comment by ssut** [comment]
Ahh I see, I thought it was yours. I therefore, wait for a PR of it otherwise I'll merge it after I make a PR by myself if it doesn't matter.

**Comment by alexanderadam** [comment]
Awesome! Thank you! :tada: 
Большое спасибо @GeNiuS69!
